version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vetcare-postgres
    environment:
      POSTGRES_DB: vetcare_db
      POSTGRES_USER: vetcare_user
      POSTGRES_PASSWORD: vetcare_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_vetcare_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vetcare-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vetcare.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_vetcare_data:
